New configure.in now tries to see if the netcdf library requires HDF5 libraries as well. All files created by aclocal/autoconf/automake are updated as well.
git-svn-id: http://svn.eol.ucar.edu/svn/rdss/trunk/suds@8389 3f9b6c58-9310-455a-aec6-8b30269ab333

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4965,15 +4965,14 @@ fi
 
 
 #
-# netCDF, rdssutil, rdssui, and rdssgraph libraries
+# netCDF
 #
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for ncopen in -lnetcdf" >&5
-$as_echo_n "checking for ncopen in -lnetcdf... " >&6; }
-if ${ac_cv_lib_netcdf_ncopen+:} false; then :
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for library containing ncopen" >&5
+$as_echo_n "checking for library containing ncopen... " >&6; }
+if ${ac_cv_search_ncopen+:} false; then :
   $as_echo_n "(cached) " >&6
 else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lnetcdf  $LIBS"
+  ac_func_search_save_LIBS=$LIBS
 cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 
@@ -4992,28 +4991,108 @@ return ncopen ();
   return 0;
 }
 _ACEOF
-if ac_fn_c_try_link "$LINENO"; then :
-  ac_cv_lib_netcdf_ncopen=yes
-else
-  ac_cv_lib_netcdf_ncopen=no
+for ac_lib in '' netcdf; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_search_ncopen=$ac_res
 fi
 rm -f core conftest.err conftest.$ac_objext \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
+    conftest$ac_exeext
+  if ${ac_cv_search_ncopen+:} false; then :
+  break
 fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_netcdf_ncopen" >&5
-$as_echo "$ac_cv_lib_netcdf_ncopen" >&6; }
-if test "x$ac_cv_lib_netcdf_ncopen" = xyes; then :
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBNETCDF 1
-_ACEOF
-
-  LIBS="-lnetcdf $LIBS"
+done
+if ${ac_cv_search_ncopen+:} false; then :
 
 else
-  echo "NetCDF library not found.  NetCDF use is disabled."
+  ac_cv_search_ncopen=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_search_ncopen" >&5
+$as_echo "$ac_cv_search_ncopen" >&6; }
+ac_res=$ac_cv_search_ncopen
+if test "$ac_res" != no; then :
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
 fi
 
+# If finding netCDF fails the first time, try adding HDF libraries and see if
+# that fixes things...
+if test "$ac_cv_search_ncopen" = "no"; then
+  unset ac_cv_search_ncopen # remove the now-cached value so we can try again
+  extra_libs="-lhdf5_hl -lhdf5"
+  { $as_echo "$as_me:${as_lineno-$LINENO}: checking for library containing ncopen" >&5
+$as_echo_n "checking for library containing ncopen... " >&6; }
+if ${ac_cv_search_ncopen+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char ncopen ();
+int
+main ()
+{
+return ncopen ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' netcdf; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib $extra_libs $ac_func_search_save_LIBS"
+  fi
+  if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_search_ncopen=$ac_res
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext
+  if ${ac_cv_search_ncopen+:} false; then :
+  break
+fi
+done
+if ${ac_cv_search_ncopen+:} false; then :
+
+else
+  ac_cv_search_ncopen=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_search_ncopen" >&5
+$as_echo "$ac_cv_search_ncopen" >&6; }
+ac_res=$ac_cv_search_ncopen
+if test "$ac_res" != no; then :
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+fi
+
+  if test "$ac_cv_search_ncopen" = "no"; then
+	  echo "NetCDF library not found."
+	  exit 1
+	fi
+	LIBS="$LIBS $extra_libs"
+fi
+HAVE_LIB_NETCDF=1
+
+# rdssutil, rdssui, and rdssgraph libraries
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for fixdir in -lrdssutil" >&5
 $as_echo_n "checking for fixdir in -lrdssutil... " >&6; }
 if ${ac_cv_lib_rdssutil_fixdir+:} false; then :
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -73,10 +73,24 @@ AC_CHECK_LIB([Xaw], [XawInitializeWidgetSet], ,
 	[echo "Cannot find Athena widget library libXaw"; exit 1])
 
 #
-# netCDF, rdssutil, rdssui, and rdssgraph libraries
+# netCDF
 #
-AC_CHECK_LIB([netcdf], [ncopen], , 
-	[echo "NetCDF library not found.  NetCDF use is disabled."])
+AC_SEARCH_LIBS([ncopen], [netcdf], , )
+# If finding netCDF fails the first time, try adding HDF libraries and see if 
+# that fixes things...
+if test "$ac_cv_search_ncopen" = "no"; then
+  unset ac_cv_search_ncopen # remove the now-cached value so we can try again
+  extra_libs="-lhdf5_hl -lhdf5"
+  AC_SEARCH_LIBS([ncopen], [netcdf], , , [$extra_libs])
+  if test "$ac_cv_search_ncopen" = "no"; then
+	  echo "NetCDF library not found."
+	  exit 1
+	fi
+	LIBS="$LIBS $extra_libs"
+fi
+HAVE_LIB_NETCDF=1
+	
+# rdssutil, rdssui, and rdssgraph libraries
 AC_CHECK_LIB([rdssutil], [fixdir], , 
 	[echo "Cannot find rdssutil library"; exit 1])
 AC_CHECK_LIB([rdssui], [ui_reset], , 
